// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

export const DESTROY_ARTWORKS_SUCCESS = 'DESTROY_ARTWORKS_SUCCESS'
export const FETCH_ARTWORKS_FAILURE = 'FETCH_ARTWORKS_FAILURE'
export const FETCH_ARTWORKS_SUCCESS = 'FETCH_ARTWORKS_SUCCESS'
export const STORE_ARTWORK_SUCCESS = 'STORE_ARTWORK_SUCCESS'
export const UPDATE_ARTWORK_SUCCESS = 'UPDATE_ARTWORK_SUCCESS'

export const DESTROY_UPLOAD_FAILURE = 'DESTROY_UPLOAD_FAILURE'
export const DESTROY_UPLOAD_SUCCESS = 'DESTROY_UPLOAD_SUCCESS'
export const FETCH_UPLOADS_FAILURE = 'FETCH_UPLOADS_FAILURE'
export const FETCH_UPLOADS_SUCCESS = 'FETCH_UPLOADS_SUCCESS'

export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE'
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'

export const FETCH_BIOGRAPHY_SUCCESS = 'FETCH_BIOGRAPHY_SUCCESS'

export const FETCH_WELCOME_SUCCESS = 'FETCH_WELCOME_SUCCESS'
